# Generated by Django 3.0.7 on 2020-07-24 11:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_order_order_quantity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_auto_20200721_1818'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favourites',
            fields=[
                ('favourites_id', models.AutoField(primary_key=True, serialize=False)),
                ('products', models.ManyToManyField(blank=True, to='shop.Product')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
