# Generated by Django 3.0.7 on 2020-07-19 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('color_id', models.AutoField(primary_key=True, serialize=False)),
                ('color_name', models.CharField(max_length=10)),
                ('color_code', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Sizes',
            fields=[
                ('size_id', models.AutoField(primary_key=True, serialize=False)),
                ('size_name', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_title', models.CharField(max_length=30)),
                ('product_headline', models.CharField(max_length=50)),
                ('product_img', models.ImageField(upload_to='')),
                ('product_price', models.IntegerField()),
                ('product_count', models.IntegerField(default=1)),
                ('product_desc', models.TextField(max_length=1000)),
                ('product_category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shop.Category')),
                ('product_colors_avalable', models.ManyToManyField(to='shop.Color')),
                ('product_sizes_avalable', models.ManyToManyField(to='shop.Sizes')),
            ],
        ),
    ]
