# Generated by Django 3.0.7 on 2020-07-19 11:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0003_auto_20200719_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_avg_rating',
            field=models.IntegerField(default=5),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('review_comment', models.CharField(max_length=100)),
                ('review_stars', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('review_date', models.DateTimeField(auto_now=True)),
                ('review_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Product')),
                ('review_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='product_reviews',
            field=models.ManyToManyField(to='shop.Review'),
        ),
    ]
