# Generated by Django 3.0.7 on 2020-07-21 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20200719_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_reviews',
            field=models.ManyToManyField(blank=True, null=True, to='shop.Review'),
        ),
    ]
