# Generated by Django 3.0.7 on 2020-07-21 10:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0005_auto_20200721_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_reviews',
            field=models.ManyToManyField(blank=True, to='shop.Review'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_amount', models.IntegerField()),
                ('order_payment_type', models.CharField(choices=[('COD', 'COD'), ('ONLINE', 'ONLINE')], max_length=10)),
                ('order_payment_due', models.BooleanField(default=True)),
                ('order_date', models.DateTimeField(auto_now=True)),
                ('order_status', models.CharField(choices=[('Processing', 'Processing'), ('Dispatched', 'Dispatched'), ('On the way', 'On the way'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Processing', max_length=20)),
                ('order_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Product')),
                ('order_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
