# Generated by Django 3.0.7 on 2020-07-21 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20200721_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
